server:
  port: 8080

unit-swagger-api:
  enabled: true
  uriPrefix: xx
  serviceDebug: true
  annotationPath: org.springframework.stereotype.Servicea
  path:
    - com.service.*
  header:
    - xx:144
